### ISSUE TITLE
Re-use/mimick errno API

### ISSUE THREAD

**Issue by aartaka** [eretsym/libcfg#2]
While `errno` is not the best type of error handling there is. But it's idiomatic and allows for quick-and-dirty error reporting. My proposal is: mimick `errno` instead of using the `last_error` approach (which is thread-unsafe compared to `errno`). Here's how the example code would look like with `errno`-like approach (I use kernel coding style, so bear with me):
``` C
// I removed the != 0 clause, because any non-zero number is
// considered true.
if (cfg_load(&cfg, "./test_1.cfg")) {
        // Alternative:
        // cfg_perror(cfg_strerror(cfg_error));
        cfg_perror(NULL);
        // This one's unnecessary, because we have cfg_error.
        // status = 1;
        goto main_free;
}
```

And here's a possible (yet fragile) implementation for all the errors I `grep`-ed in your code:
``` C
int cfg_error = 0;

enum cfg_errors {
        CFG_EMEM = 1,
        CFG_EINVINT,
        CFG_EINVFLOAT,
        CFG_EINVSTRING,
        CFG_EINVBOOL,
        CFG_EINVNULL,
        CFG_EINVID,
        CFG_ERANGE,
        CFG_EAPPLY,
        CFG_EPARSE,
        CFG_EOPEN,
        CFG_ESIZE,
        CFG_ESEEK,
        CFG_EMAP,
        CFG_ENEXIST,
        CFG_EWTF,
};

int errstr[] = {
        [CFG_EMEM]       = "Out of memory",
        [CFG_EINVINT]    = "Invalid integer",
        [CFG_EINVFLOAT]  = "Invalid float",
        [CFG_EINVSTRING] = "Invalid string",
        [CFG_EINVBOOL]   = "Invalid boolean",
        [CFG_EINVNULL]   = "Invalid value: NULL",
        [CFG_EINVID]     = "Invalid identifier",
        [CFG_ERANGE]     = "Out of range",
        [CFG_EAPPLY]     = "Failed to add boolean setting",
        [CFG_EPARSE]     = "Parsing failed",
        [CFG_EOPEN]      = "Failed to open",
        [CFG_ESIZE]      = "Failed to get file size",
        [CFG_ESEEK]      = "Failed to seek end of file",
        [CFG_EMAP]       = "Failed to map file content to memory",
        [CFG_ENEXIST]    = "Setting doesn't exist",
        [CFG_EWTF]       = "Huh?",
};

char *cfg_strerror (int err)
{
        return errstr[err];
}

void cfg_perror (const char *message)
{
        if (message)
                puts(message);
        else
                puts(cfg_strerror(cfg_error));
}
```
It's short and pretty.

Also note that `CFG_EMEM`, and file-related errors might be better handled by [POSIX `error.h`](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/errno.h.html) instead of home-grown solution.

**Comment by eretsym** [comment]
i'm not sure the code example you provided is thread-safe, nor having a global variable makes it thread-safe (correct me if i'm wrong). however i like this idiomatic approach.

**Comment by aartaka** [comment]
Yeah, my example code is not thread-safe, so the biggest gain is clarity. And it's just an example code, so lots of things might be improved in the actual implementation.

I can see the value in `!= 0` point and in the `status = 1` too. I'm just suggesting to use the `cfg_errno` for simple cases.

Feel free to close if that's a no-goal.

**Comment by eretsym** [comment]
I started working on that error system, but don't know the intricacies of C multithreading. I'll do what I can

**Comment by eretsym** [comment]
@aartaka would you like to review the pull request and suggest any changes if someting appears wrong? I also updated the example to show how to use the updated API
